defaults:
  - _self_
  - debug: default
  - paths: data
  - hyperparameters: default

meta:
  expected_classes: ["angry", "disgust", "fear", "happy", "neutral", "sad", "surprise"]
  expected_mode: "L"
  img_size: 48